"""updated the time

Revision ID: 11bef3d5f8df
Revises: b92c690d86a7
Create Date: 2025-10-05 14:17:44.500991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11bef3d5f8df'
down_revision: Union[str, Sequence[str], None] = 'b92c690d86a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbadges', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('userbadges', sa.Column('badge_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'userbadges', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'userbadges', 'badges', ['badge_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userbadges', type_='foreignkey')
    op.drop_constraint(None, 'userbadges', type_='foreignkey')
    op.drop_column('userbadges', 'badge_id')
    op.drop_column('userbadges', 'user_id')
    # ### end Alembic commands ###
