"""Add app_refresh_token columns

Revision ID: 9a2d579c08cf
Revises: 
Create Date: 2025-09-26 22:33:14.534259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2d579c08cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('app_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('app_refresh_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'app_refresh_token_expires_at')
    op.drop_column('users', 'app_refresh_token')
    # ### end Alembic commands ###
