"""added some new column

Revision ID: b92c690d86a7
Revises: 4914f78a56f7
Create Date: 2025-10-05 13:53:57.224124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b92c690d86a7'
down_revision: Union[str, Sequence[str], None] = '4914f78a56f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('description', sa.String(), nullable=False))
    op.add_column('badges', sa.Column('rarity', sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY', name='rarityenum'), nullable=False))
    op.add_column('badges', sa.Column('category', sa.Enum('ACHIEVEMENT', 'PERFORMANCE', 'CREATIVITY', 'THEME', 'SOCIAL', 'PARTICIPATION', 'SPECIAL', name='categoryenum'), nullable=False))
    op.add_column('badges', sa.Column('requirements', sa.String(), nullable=False))
    op.add_column('badges', sa.Column('badge_image', sa.String(), nullable=False))
    op.add_column('badges', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('badges', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('badges', 'Rarity')
    op.drop_column('badges', 'Description')
    op.add_column('campaigns', sa.Column('description', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('isVoting', sa.Boolean(), nullable=True))
    op.add_column('campaigns', sa.Column('isPosting', sa.Boolean(), nullable=True))
    op.add_column('campaigns', sa.Column('isEnded', sa.Boolean(), nullable=True))
    op.drop_column('campaigns', 'end_date')
    op.add_column('memes', sa.Column('title', sa.String(), nullable=False))
    op.add_column('memes', sa.Column('score', sa.Integer(), nullable=True))
    op.alter_column('memes', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'memes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'memes', 'campaigns', ['campaign_id'], ['id'])
    op.drop_column('memes', 'downvotes')
    op.drop_column('memes', 'upvotes')
    op.add_column('userbadges', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('userbadges', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('CREATOR', 'ADMIN', 'USER', name='roleenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('userbadges', 'updated_at')
    op.drop_column('userbadges', 'created_at')
    op.add_column('memes', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('memes', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'memes', type_='foreignkey')
    op.drop_constraint(None, 'memes', type_='foreignkey')
    op.alter_column('memes', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('memes', 'score')
    op.drop_column('memes', 'title')
    op.add_column('campaigns', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('campaigns', 'isEnded')
    op.drop_column('campaigns', 'isPosting')
    op.drop_column('campaigns', 'isVoting')
    op.drop_column('campaigns', 'description')
    op.add_column('badges', sa.Column('Description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('badges', sa.Column('Rarity', postgresql.ENUM('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY', name='rarityenum'), autoincrement=False, nullable=False))
    op.drop_column('badges', 'updated_at')
    op.drop_column('badges', 'created_at')
    op.drop_column('badges', 'badge_image')
    op.drop_column('badges', 'requirements')
    op.drop_column('badges', 'category')
    op.drop_column('badges', 'rarity')
    op.drop_column('badges', 'description')
    # ### end Alembic commands ###
